DROP TABLE IF EXISTS magnets;

CREATE TABLE IF NOT EXISTS magnet_types (
id SERIAL PRIMARY KEY,
type VARCHAR(255),
created_at BIGINT
);

CREATE TABLE IF NOT EXISTS users (
id SERIAL PRIMARY KEY,
username VARCHAR(255),
email VARCHAR(255)
);

CREATE TABLE magnets (
id SERIAL PRIMARY KEY,
content VARCHAR(255),
x INTEGER,
y INTEGER,
color VARCHAR(255),
type_id INTEGER NOT NULL REFERENCES magnet_types(id)
);



